const VERSES = [
  { text: "Others went out to sea in ships, conducting trade on the mighty waters.", ref: "Psalm 107:23", moods: ["sea", "sailing", "journey"] },
  { text: "He calmed the storm to a whisper, and the waves of the sea were hushed.", ref: "Psalm 107:29", moods: ["storm", "sea", "peace"] },
  { text: "They rejoiced in the silence, and He guided them to the harbor they desired.", ref: "Psalm 107:30", moods: ["sea", "sailing", "journey"] },
  { text: "Then Jesus got up and rebuked the wind and the sea. \"Silence!\" He commanded. \"Be still!\" And the wind died down, and it was perfectly calm.", ref: "Mark 4:39", moods: ["storm", "wind", "sea"] },
  { text: "You rule the raging sea; when its waves mount up, You still them.", ref: "Psalm 89:9", moods: ["sea", "storm"] },
  { text: "Above the roar of many waters, the mighty breakers of the sea, the LORD on high is majestic.", ref: "Psalm 93:4", moods: ["sea", "water", "wonder"] },
  { text: "When you pass through the waters, I will be with you; and when you go through the rivers, they will not overwhelm you.", ref: "Isaiah 43:2", moods: ["water", "journey", "peace"] },
  { text: "Trust in the LORD with all your heart, and lean not on your own understanding.", ref: "Proverbs 3:5", moods: ["journey", "peace"] },
  { text: "In all your ways acknowledge Him, and He will make your paths straight.", ref: "Proverbs 3:6", moods: ["journey", "growth"] },
  { text: "The LORD will watch over your coming and going, both now and forevermore.", ref: "Psalm 121:8", moods: ["journey", "peace"] },
  { text: "Then they were willing to take Him into the boat, and at once the boat reached the shore where they were heading.", ref: "John 6:21", moods: ["sea", "sailing", "journey"] },
  { text: "We have this hope as an anchor for the soul, firm and secure.", ref: "Hebrews 6:19", moods: ["sea", "sailing", "peace"] },
  { text: "The rain fell, the torrents raged, and the winds blew and beat against that house; yet it did not fall, because its foundation was on the rock.", ref: "Matthew 7:25", moods: ["rain", "storm", "wind"] },
  { text: "For He says to the snow, 'Fall on the earth,' and to the gentle rain, 'Pour out a mighty downpour.'", ref: "Job 37:6", moods: ["snow", "rain", "storm"] },
  { text: "He sends forth His word and melts them; He unleashes His winds, and the waters flow.", ref: "Psalm 147:18", moods: ["wind", "water"] },
  { text: "Lightning and hail, snow and clouds, powerful wind fulfilling His word.", ref: "Psalm 148:8", moods: ["storm", "wind", "snow"] },
  { text: "His path is in the whirlwind and storm, and clouds are the dust beneath His feet.", ref: "Nahum 1:3", moods: ["storm", "wind", "wonder"] },
  { text: "Then the LORD hurled a great wind upon the sea, and such a violent storm arose that the ship was in danger of breaking apart.", ref: "Jonah 1:4", moods: ["storm", "wind", "sea"] },
  { text: "For just as rain and snow fall from heaven and do not return without watering the earth, making it bud and sprout, and providing seed to sow and food to eat.", ref: "Isaiah 55:10", moods: ["rain", "snow", "growth"] },
  { text: "He spreads the snow like wool; He scatters the frost like ashes.", ref: "Psalm 147:16", moods: ["snow", "season"] },
  { text: "Though your sins are like scarlet, they will be as white as snow; though they are as red as crimson, they will become like wool.", ref: "Isaiah 1:18", moods: ["snow", "renewal"] },
  { text: "To everything there is a season, and a time for every purpose under heaven.", ref: "Ecclesiastes 3:1", moods: ["season", "wonder"] },
  { text: "As long as the earth endures, seedtime and harvest, cold and heat, summer and winter, day and night shall never cease.", ref: "Genesis 8:22", moods: ["season", "day", "night"] },
  { text: "He is like a tree planted by streams of water, yielding its fruit in season, whose leaf does not wither, and who prospers in all he does.", ref: "Psalm 1:3", moods: ["growth", "water", "season"] },
  { text: "From where the sun rises to where it sets, the name of the LORD is praised.", ref: "Psalm 113:3", moods: ["dawn", "dusk", "day"] },
  { text: "For His anger is fleeting, but His favor lasts a lifetime. Weeping may stay the night, but joy comes in the morning.", ref: "Psalm 30:5", moods: ["night", "dawn", "renewal"] },
  { text: "Because of the loving devotion of the LORD we are not consumed, for His mercies never fail.", ref: "Lamentations 3:22", moods: ["renewal", "peace"] },
  { text: "They are new every morning; great is Your faithfulness!", ref: "Lamentations 3:23", moods: ["dawn", "renewal"] },
  { text: "The heavens declare the glory of God; the skies proclaim the work of His hands.", ref: "Psalm 19:1", moods: ["stars", "wonder", "day"] },
  { text: "But for you who fear My name, the sun of righteousness will rise with healing in its wings, and you will go out and leap like calves from the stall.", ref: "Malachi 4:2", moods: ["dawn", "light"] },
  { text: "The Mighty One, God the LORD, speaks and summons the earth from where the sun rises to where it sets.", ref: "Psalm 50:1", moods: ["dawn", "dusk", "day"] },
  { text: "Let me hear Your loving devotion in the morning, for I have put my trust in You.", ref: "Psalm 143:8", moods: ["dawn", "peace"] },
  { text: "The sun will not strike you by day, nor the moon by night.", ref: "Psalm 121:6", moods: ["day", "night"] },
  { text: "He determines the number of the stars; He calls them each by name.", ref: "Psalm 147:4", moods: ["stars", "night", "wonder"] },
  { text: "When I behold Your heavens, the work of Your fingers, the moon and the stars, which You have set in place.", ref: "Psalm 8:3", moods: ["stars", "night", "wonder"] },
  { text: "The moon and stars to govern the night. His loving devotion endures forever.", ref: "Psalm 136:9", moods: ["night", "stars"] },
  { text: "Then the wise will shine like the brightness of the heavens, and those who lead many to righteousness will shine like the stars forever and ever.", ref: "Daniel 12:3", moods: ["stars", "wonder", "light"] },
  { text: "The day is Yours, and also the night; You established the moon and the sun.", ref: "Psalm 74:16", moods: ["day", "night"] },
  { text: "Day after day they pour forth speech; night after night they reveal knowledge.", ref: "Psalm 19:2", moods: ["day", "night", "stars"] },
  { text: "Peace I leave with you; My peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled; do not be afraid.", ref: "John 14:27", moods: ["peace"] },
  { text: "Be still and know that I am God; I will be exalted among the nations, I will be exalted over the earth.", ref: "Psalm 46:10", moods: ["peace", "wonder"] },
  { text: "You will keep in perfect peace the steadfast of mind, because he trusts in You.", ref: "Isaiah 26:3", moods: ["peace"] },
  { text: "And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.", ref: "Philippians 4:7", moods: ["peace"] },
  { text: "May the LORD lift up His countenance toward you and give you peace.", ref: "Numbers 6:26", moods: ["peace", "light"] },
  { text: "And why do you worry about clothes? Consider how the lilies of the field grow: They do not labor or spin.", ref: "Matthew 6:28", moods: ["growth", "wonder"] },
  { text: "The grass withers and the flowers fall, but the word of our God stands forever.", ref: "Isaiah 40:8", moods: ["growth", "season", "renewal"] },
  { text: "Those who sow in tears will reap with shouts of joy.", ref: "Psalm 126:5", moods: ["growth", "renewal"] },
  { text: "So My word that proceeds from My mouth will not return to Me empty, but it will accomplish what I please, and it will prosper where I send it.", ref: "Isaiah 55:11", moods: ["growth", "wonder"] },
  { text: "You will indeed go out with joy and be led forth in peace; the mountains and hills will burst into song before you.", ref: "Isaiah 55:12", moods: ["peace", "growth", "renewal"] },
  { text: "The Light shines in the darkness, and the darkness has not overcome it.", ref: "John 1:5", moods: ["light", "night"] },
  { text: "This is the day that the LORD has made; we will rejoice and be glad in it.", ref: "Psalm 118:24", moods: ["day", "wonder"] },
  { text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, with whom there is no change or shifting shadow.", ref: "James 1:17", moods: ["light", "wonder"] },
  { text: "The LORD is my light and my salvation, whom shall I fear? The LORD is the stronghold of my life, whom shall I dread?", ref: "Psalm 27:1", moods: ["light", "peace"] },
  { text: "The LORD is my shepherd; I shall not want.", ref: "Psalm 23:1", moods: ["peace", "growth"] },
  { text: "He makes me lie down in green pastures; He leads me beside quiet waters.", ref: "Psalm 23:2", moods: ["water", "peace", "growth"] },
  { text: "He has made everything beautiful in its time. He has also set eternity in the hearts of men.", ref: "Ecclesiastes 3:11", moods: ["wonder", "season"] }
];
if (typeof module !== "undefined") { module.exports = VERSES; }
